#!/bin/bash

# Update and install HAProxy
sudo apt update
sudo apt install -y haproxy

# Backup the default HAProxy configuration
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Create a new HAProxy configuration
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOL
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend app
    bind *:80
    default_backend backend_servers

backend backend_servers
    balance roundrobin
    server web-01 100.26.209.81:80 check
    server web-02 54.144.133.181:80 check
EOL

# Enable HAProxy to start on boot
sudo systemctl enable haproxy

# Restart HAProxy
sudo systemctl restart haproxy

